add upgrade task to upgrade to a newer buildpack version, init task will reinstall current buildpack version (#17)

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -12,20 +12,20 @@ vars:
   SCRIPTS_FOLDER: "{{.BUILDPACK_FOLDER}}/scripts"
   BUILDPACK_VERSION:
     sh: >-
-      BUILDPACK_VERSION=$BRANCH;
+      BUILDPACK_VERSION=$VERSION;
       if [ "$BUILDPACK_VERSION" == "" ]; then
-      BUILDPACK_VERSION=$(cat buildpack/tmp/VERSION 2> /dev/null);
+        BUILDPACK_VERSION="$(grep -e "^#BUILDPACK_VERSION:" Taskfile.yml 2>/dev/null | grep -o -e '[^:]*$')";
       fi;
       if [ "$BUILDPACK_VERSION" == "" ]; then
-      BUILDPACK_VERSION=$(git ls-remote -t git@github.com:itsmethemojo/buildpack.git | awk '{print $2}' | cut -d '/' -f 3 | cut -d '^' -f 1 | tail -1);
+        BUILDPACK_VERSION=$(git ls-remote -t git@github.com:itsmethemojo/buildpack.git | awk '{print $2}' | cut -d '/' -f 3 | cut -d '^' -f 1 | tail -1);
       fi;
       echo $BUILDPACK_VERSION;
   DOWNLOAD_TASK:
     sh: >-
-      if [ "$BRANCH" == "_local_copy" ]; then
-      echo _copy_from_local;
+      if [ "$VERSION" == "_test_local_copy" ]; then
+        echo _copy_from_local;
       else
-      echo _download_from_git;
+        echo _download_from_git;
       fi
   ABSOLUTE_PROJECT_ROOT:
     sh: "pwd"
@@ -41,10 +41,10 @@ vars:
       CONFIG_FILE=buildpack/config/tasks.env
       RETURN_CONTAINER_NAME=buildpack-deps;
       if [ "$(grep -e "^${name}_container=" $CONFIG_FILE 2>/dev/null | grep -o -e '[^=]*$')" != "" ]; then
-      RETURN_CONTAINER_NAME="$(grep -e "^${name}_container=" $CONFIG_FILE 2>/dev/null | grep -o -e '[^=]*$')";
+        RETURN_CONTAINER_NAME="$(grep -e "^${name}_container=" $CONFIG_FILE 2>/dev/null | grep -o -e '[^=]*$')";
       fi;
       if [ "$(grep -e "^${name}_dockerfile=" $CONFIG_FILE 2>/dev/null | grep -o -e '[^=]*$')" != "" ]; then
-      RETURN_CONTAINER_NAME="buildpack-{{.PROJECT_FOLDER_NAME}}-task-${name}";
+        RETURN_CONTAINER_NAME="buildpack-{{.PROJECT_FOLDER_NAME}}-task-${name}";
       fi;
       echo $RETURN_CONTAINER_NAME;
   TASK_DOCKERFILE_PATH:
@@ -54,35 +54,41 @@ vars:
 tasks:
 
   add:
-    deps: [ _check-init-needed ]
+    desc: name=new-task-name task add           adds a new task that can be later used with task new-task-name
+    deps: [ _check_init_needed ]
     cmds:
-      - task: _create-task-script
-      - task: _update-taskfile
+      - task: _create_task_script
+      - task: _update_taskfile
 
   version:
-    deps: [ _check-init-needed ]
+    desc: task version                          prints the current used version of task
+    deps: [ _check_init_needed ]
     cmds:
-      - task: _print-version
+      - task: _print_version
 
   init:
+    desc: task init                             setup initial config and downloads needed dependencies
     cmds:
-      - task: _download-buildpack
-      - task: _create-config-files
-      - task: _update-gitignore
-      - task: _update-taskfile
+      - task: _download_buildpack
+      - task: _create_config_files
+      - task: _update_gitignore
+      - task: _update_taskfile
 
-  run:
-    deps: [ _check-init-needed ]
+  upgrade:
+    desc: task upgrade                          will upgrade your buildpack version to the most current available
     cmds:
-      - task: _start_watch_run
-      - task: _print-version
-      - task: _build_task_container
-      - task: _run_task
-      - task: _stop_watch_run
+      - cmd: >-
+          NEWEST_VERSION=$(git ls-remote -t git@github.com:itsmethemojo/buildpack.git | awk '{print $2}' | cut -d '/' -f 3 | cut -d '^' -f 1 | tail -1);
+          if [ "$NEWEST_VERSION" == "{{.BUILDPACK_VERSION}}" ]; then
+            echo 'buildpack is already on the newest version';
+          else
+            VERSION=$NEWEST_VERSION task init
+          fi
+        silent: true
 
   # private targets
 
-  _add-targets-for-available-tasks-to-taskfile:
+  _add_targets_for_available_tasks_to_taskfile:
     cmds:
       - cmd: >-
           for SCRIPT_FILE in $(ls -1 {{.SCRIPTS_FOLDER}} 2>/dev/null | sed -e 's/\..*$//'); do
@@ -94,16 +100,16 @@ tasks:
     cmds:
       - cmd: >-
           if [ "{{.TASK_DOCKERFILE_PATH}}" != "" ]; then
-          docker build -t {{.TASK_CONTAINER_NAME}} -f "{{.TASK_DOCKERFILE_PATH}}" $(dirname "{{.TASK_DOCKERFILE_PATH}}");
+            docker build -t {{.TASK_CONTAINER_NAME}} -f "{{.TASK_DOCKERFILE_PATH}}" $(dirname "{{.TASK_DOCKERFILE_PATH}}");
           fi;
         silent: true
 
-  _check-init-needed:
+  _check_init_needed:
     cmds:
       - cmd: >-
           if [ ! -f "{{.BASH_SCRIPT_TEMPLATE}}" ]; then
-          echo 'Important files missing. Buildpack seems not be installed. Run "task init" to fix that.';
-          exit 1;
+            echo 'Important files missing. Buildpack seems not be installed. Run "task init" to fix that.';
+            exit 1;
           fi
         silent: true
 
@@ -115,22 +121,22 @@ tasks:
           cp {{.BUILDPACK_FOLDER}}/../../../Taskfile.yml {{.BUILDPACK_TMP_FOLDER}}/Taskfile.yml;
         silent: true
 
-  _copy-taskfile-from-download:
+  _copy_taskfile_from_download:
     cmds:
-      - cmd: >
-          echo -e "#BUILDPACK VERSION: {{.BUILDPACK_VERSION}}\n" > Taskfile.yml &&
+      - cmd: >-
+          echo -e "#BUILDPACK_VERSION: {{.BUILDPACK_VERSION}}\n" > Taskfile.yml &&
           cat {{.BUILDPACK_TMP_FOLDER}}/Taskfile.yml >> Taskfile.yml
         silent: true
 
-  _create-config-files:
+  _create_config_files:
     cmds:
       - cmd: >-
           mkdir -p {{.CONFIG_FOLDER}}/docker;
           touch {{.CONFIG_FOLDER}}/tasks.env
         silent: true
 
-  _create-task-script:
-    deps: [ _has-name-parameter ]
+  _create_task_script:
+    deps: [ _has_name_parameter ]
     cmds:
       - cmd: >-
           mkdir -p {{.SCRIPTS_FOLDER}};
@@ -139,12 +145,10 @@ tasks:
           cat {{.BASH_SCRIPT_TEMPLATE}} >> {{.SCRIPTS_FOLDER}}/{{.name}}.sh
         silent: true
 
-  _download-buildpack:
-    deps: [ _empty-download-folder ]
+  _download_buildpack:
+    deps: [ _empty_download_folder ]
     cmds:
       - task: "{{.DOWNLOAD_TASK}}"
-        silent: true
-      - cmd: "echo {{.BUILDPACK_VERSION}} > {{.BUILDPACK_TMP_FOLDER}}/VERSION"
         silent: true
 
   _download_from_git:
@@ -158,35 +162,44 @@ tasks:
           "
         silent: true
 
-  _empty-download-folder:
+  _empty_download_folder:
     cmds:
       - cmd: >-
           rm -rf {{.BUILDPACK_TMP_FOLDER}};
           mkdir -p {{.BUILDPACK_TMP_FOLDER}}
         silent: true
 
-  _has-name-parameter:
+  _has_name_parameter:
     cmds:
       - cmd: >-
           if [ "$name" == "" ]; then
-          echo 'missing Parameter name! Usage: name="my-task" task add';
-          exit 1;
+            echo 'missing Parameter name! Usage: name="my-task" task add';
+            exit 1;
           fi
         silent: true
 
-  _print-version:
+  _print_version:
     cmds:
       - cmd: >-
-          echo Version: {{.BUILDPACK_VERSION}};
+          echo Buildpack Version: {{.BUILDPACK_VERSION}};
         silent: true
+
+  _run:
+    deps: [ _check_init_needed ]
+    cmds:
+      - task: _start_watch_run
+      - task: _print_version
+      - task: _build_task_container
+      - task: _run_task
+      - task: _stop_watch_run
 
   _run_task:
     cmds:
       - cmd: >-
           if [ -f "/.dockerenv" ]; then
-          bash {{.TASK_DIR_IN_CONTAINER}}/{{.TASK_SCRIPT_PATH}};
+            bash {{.TASK_DIR_IN_CONTAINER}}/{{.TASK_SCRIPT_PATH}};
           else
-          docker run {{.TASK_CONTAINER_MOUNT_PARAMETERS}} -w {{.TASK_DIR_IN_CONTAINER}} {{.TASK_CONTAINER_NAME}} bash {{.TASK_SCRIPT_PATH}};
+            docker run {{.TASK_CONTAINER_MOUNT_PARAMETERS}} -w {{.TASK_DIR_IN_CONTAINER}} {{.TASK_CONTAINER_NAME}} bash {{.TASK_SCRIPT_PATH}};
           fi;
         silent: true
 
@@ -203,19 +216,19 @@ tasks:
           rm {{.BUILDPACK_TMP_FOLDER}}/start-watch-$name
         silent: true
 
-  _update-gitignore:
+  _update_gitignore:
     cmds:
       - cmd: >-
           if [ ! -f .gitignore ]; then
-          echo "/{{.BUILDPACK_TMP_FOLDER}}"/ > .gitignore;
+            echo "/{{.BUILDPACK_TMP_FOLDER}}"/ > .gitignore;
           fi;
           if [ "$(grep "/{{.BUILDPACK_TMP_FOLDER}}/" .gitignore | wc -l)" = "0" ]; then
-          echo "/{{.BUILDPACK_TMP_FOLDER}}/" >> .gitignore;
+            echo "/{{.BUILDPACK_TMP_FOLDER}}/" >> .gitignore;
           fi
         silent: true
 
-  _update-taskfile:
+  _update_taskfile:
     cmds:
-      - task: _copy-taskfile-from-download
-      - task: _add-targets-for-available-tasks-to-taskfile
-      - task: _print-version
+      - task: _copy_taskfile_from_download
+      - task: _add_targets_for_available_tasks_to_taskfile
+      - task: _print_version
