rename to .dckrz

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -2,10 +2,9 @@
 # remove any expensive container usage from vars initialization
 # move run.sh into taskfile
 # use buildpack:: grouping for public targets
-# determine latest version when needed in init task
 # group directory_vars in DIRECTORY_
 
-
+#.dckrz
 
 
 
@@ -14,13 +13,14 @@ version: '2'
 expansions: 5
 
 vars:
-  BUILDPACK_REPOSITORY: 'https://github.com/itsmethemojo/buildpack.git'
-  BUILDPACK_FOLDER: buildpack
-  BUILDPACK_TMP_FOLDER: "{{.BUILDPACK_FOLDER}}/tmp"
-  CONFIG_FOLDER: "{{.BUILDPACK_FOLDER}}/config"
-  BASH_SCRIPT_TEMPLATE: "{{.BUILDPACK_TMP_FOLDER}}/bash/templates/run-task.sh"
-  TASK_TARGET_TEMPLATE: "{{.BUILDPACK_TMP_FOLDER}}/taskfiles/templates/target-to-run-task.yml"
-  SCRIPTS_FOLDER: "{{.BUILDPACK_FOLDER}}/scripts"
+  GIT_REPOSITORY: 'https://github.com/itsmethemojo/buildpack.git'
+  API_TAGS: 'https://api.github.com/repos/itsmethemojo/buildpack/tags'
+  DIRECTORY_DCKRZ: .dckrz
+  DIRECTORY_DCKRZ_TMP: "{{.DIRECTORY_DCKRZ}}/tmp"
+  DIRECTORY_CONFIG: "{{.DIRECTORY_DCKRZ}}/config"
+  DIRECTORY_SCRIPTS: "{{.DIRECTORY_DCKRZ}}/scripts"
+  FILE_BASH_SCRIPT_TEMPLATE: "{{.DIRECTORY_DCKRZ_TMP}}/bash/templates/run-task.sh"
+  FILE_TARGET_TEMPLATE: "{{.DIRECTORY_DCKRZ_TMP}}/taskfiles/templates/target-to-run-task.yml"
   TEST_MODE:
     sh: >-
       if [ -f "../tests.bats" ]; then
@@ -28,16 +28,16 @@ vars:
       else
       echo 0;
       fi;
-  BUILDPACK_VERSION:
+  DCKRZ_VERSION:
     sh: >-
-      BUILDPACK_VERSION=$VERSION;
-      if [ "$BUILDPACK_VERSION" == "" ]; then
-        BUILDPACK_VERSION="$(grep -e "^#BUILDPACK_VERSION:" Taskfile.yml 2>/dev/null | grep -o -e '[^:]*$')";
+      DCKRZ_VERSION=$VERSION;
+      if [ "$DCKRZ_VERSION" == "" ]; then
+        DCKRZ_VERSION="$(grep -e "^#DCKRZ_VERSION:" Taskfile.yml 2>/dev/null | grep -o -e '[^:]*$')";
       fi;
-      if [ "$BUILDPACK_VERSION" == "" ] && [ ! -f "../tests.bats" ]; then
-        BUILDPACK_VERSION=$(docker run buildpack-deps:curl bash -c 'curl -s https://api.github.com/repos/itsmethemojo/buildpack/tags | grep "\"name\":" | head -1 | cut -d":" -f2 | cut -d"\"" -f2');
+      if [ "$DCKRZ_VERSION" == "" ] && [ ! -f "../tests.bats" ]; then
+        DCKRZ_VERSION=$(docker run buildpack-deps:curl bash -c 'curl -s https://api.github.com/repos/itsmethemojo/buildpack/tags | grep "\"name\":" | head -1 | cut -d":" -f2 | cut -d"\"" -f2');
       fi;
-      echo $BUILDPACK_VERSION;
+      echo $DCKRZ_VERSION;
   ABSOLUTE_PROJECT_ROOT:
     sh: "pwd"
   PROJECT_FOLDER_NAME:
@@ -60,7 +60,7 @@ tasks:
     cmds:
       - cmd: ./tests/run.sh | tee {{.TESTS_OUTPUT_FILE}};
         ignore_error: true
-        silent: false
+        silent: true
 
   init:
     desc: '[VERSION=version] task init                       setup initial config and downloads needed dependencies, optional parameter to select a specific version'
@@ -72,16 +72,17 @@ tasks:
       - task: _print_version
 
   upgrade:
-    desc: task upgrade                                      will upgrade your buildpack version to the most current available
+    deps: [ _check_init_needed ]
+    desc: task upgrade                                      will upgrade your DCKRZE version to the most current available
     cmds:
       - cmd: >-
-          NEWEST_VERSION=$(git ls-remote -t git@github.com:itsmethemojo/buildpack.git | awk '{print $2}' | cut -d '/' -f 3 | cut -d '^' -f 1 | tail -1);
-          if [ "$NEWEST_VERSION" == "{{.BUILDPACK_VERSION}}" ]; then
-            echo 'buildpack is already on the newest version';
+          NEWEST_VERSION=$(docker run buildpack-deps:curl bash -c 'curl -s {{.API_TAGS}} | grep "\"name\":" | head -1 | cut -d":" -f2 | cut -d"\"" -f2');
+          if [ "$NEWEST_VERSION" == "{{.DCKRZ_VERSION}}" ]; then
+            echo 'DCKRZE is already on the newest version';
           else
             VERSION=$NEWEST_VERSION task init
           fi
-        silent: false
+        silent: true
 
   version:
     desc: task version                                     prints the current used version of task
@@ -94,128 +95,122 @@ tasks:
   _check_init_needed:
     cmds:
       - cmd: >-
-          if [ ! -f "{{.BASH_SCRIPT_TEMPLATE}}" ]; then
-            echo 'Important files missing. Buildpack seems not be installed. Run "task init" to fix that.';
+          if [ ! -f "{{.FILE_BASH_SCRIPT_TEMPLATE}}" ]; then
+            echo 'Important files missing. DCKRZE seems not be installed. Run "task init" to fix that.';
             exit 1;
           fi
-        silent: false
+        silent: true
 
   _init:create_config_files:
     cmds:
       - cmd: >-
-          mkdir -p {{.CONFIG_FOLDER}}/docker;
-          touch {{.CONFIG_FOLDER}}/tasks.env
-        silent: false
+          mkdir -p {{.DIRECTORY_CONFIG}}/docker;
+          touch {{.DIRECTORY_CONFIG}}/tasks.env
+        silent: true
 
   _create_task_script:
-    deps: [ _has_name_parameter ]
     cmds:
       - cmd: >-
-          mkdir -p {{.SCRIPTS_FOLDER}};
-          touch {{.SCRIPTS_FOLDER}}/{{.name}}.sh;
-          chmod +x {{.SCRIPTS_FOLDER}}/{{.name}}.sh;
-          cat {{.BASH_SCRIPT_TEMPLATE}} >> {{.SCRIPTS_FOLDER}}/{{.name}}.sh
-        silent: false
+          if [ "$name" == "" ]; then
+            echo 'missing Parameter name! Usage: name="my-task" task add';
+            exit 1;
+          fi;
+          mkdir -p {{.DIRECTORY_SCRIPTS}};
+          touch {{.DIRECTORY_SCRIPTS}}/{{.name}}.sh;
+          chmod +x {{.DIRECTORY_SCRIPTS}}/{{.name}}.sh;
+          cat {{.FILE_BASH_SCRIPT_TEMPLATE}} >> {{.DIRECTORY_SCRIPTS}}/{{.name}}.sh
+        silent: true
 
   _init:download:
     cmds:
       - cmd: >-
-          rm -rf {{.ABSOLUTE_PROJECT_ROOT}}/{{.BUILDPACK_TMP_FOLDER}};
-          mkdir -p {{.ABSOLUTE_PROJECT_ROOT}}/{{.BUILDPACK_TMP_FOLDER}};
-          if [ {{.TEST_MODE}} -eq 1 ] && [ "{{.BUILDPACK_VERSION}}" == "" ];
+          rm -rf {{.ABSOLUTE_PROJECT_ROOT}}/{{.DIRECTORY_DCKRZ_TMP}};
+          mkdir -p {{.ABSOLUTE_PROJECT_ROOT}}/{{.DIRECTORY_DCKRZ_TMP}};
+          if [ {{.TEST_MODE}} -eq 1 ] && [ "{{.DCKRZ_VERSION}}" == "" ];
           then
-          cp -R {{.ABSOLUTE_PROJECT_ROOT}}/../../taskfiles {{.ABSOLUTE_PROJECT_ROOT}}/{{.BUILDPACK_TMP_FOLDER}}/;
-          cp -R {{.ABSOLUTE_PROJECT_ROOT}}/../../bash {{.ABSOLUTE_PROJECT_ROOT}}/{{.BUILDPACK_TMP_FOLDER}}/;
-          cp {{.ABSOLUTE_PROJECT_ROOT}}/../../Taskfile.yml {{.ABSOLUTE_PROJECT_ROOT}}/{{.BUILDPACK_TMP_FOLDER}}/Taskfile.yml;
+          cp -R {{.ABSOLUTE_PROJECT_ROOT}}/../../taskfiles {{.ABSOLUTE_PROJECT_ROOT}}/{{.DIRECTORY_DCKRZ_TMP}}/;
+          cp -R {{.ABSOLUTE_PROJECT_ROOT}}/../../bash {{.ABSOLUTE_PROJECT_ROOT}}/{{.DIRECTORY_DCKRZ_TMP}}/;
+          cp {{.ABSOLUTE_PROJECT_ROOT}}/../../Taskfile.yml {{.ABSOLUTE_PROJECT_ROOT}}/{{.DIRECTORY_DCKRZ_TMP}}/Taskfile.yml;
           else
-          docker run -v {{.ABSOLUTE_PROJECT_ROOT}}/{{.BUILDPACK_TMP_FOLDER}}:/downloads buildpack-deps
+          docker run -v {{.ABSOLUTE_PROJECT_ROOT}}/{{.DIRECTORY_DCKRZ_TMP}}:/downloads buildpack-deps
           bash -c "
-          git clone -b {{.BUILDPACK_VERSION}} --depth 1 {{.BUILDPACK_REPOSITORY}} /downloads &> /dev/null &&
+          git clone -b {{.DCKRZ_VERSION}} --depth 1 {{.GIT_REPOSITORY}} /downloads &> /dev/null &&
           rm -r /downloads/.git &&
           chmod -R 777 /downloads
           ";
           fi;
-        silent: false
-
-  _has_name_parameter:
-    cmds:
-      - cmd: >-
-          if [ "{{.name}}" == "" ]; then
-            echo 'missing Parameter name! Usage: name="my-task" task add';
-            exit 1;
-          fi
-        silent: false
+        silent: true
 
   _print_version:
     cmds:
       - cmd: >-
-          echo Buildpack Version: {{.BUILDPACK_VERSION}};
-        silent: false
+          echo DCKRZE Version: {{.DCKRZ_VERSION}};
+        silent: true
 
   _script:run:
     cmds:
       - cmd: >-
-          ls {{.BUILDPACK_TMP_FOLDER}}/;
-          if [ "{{.TASK_DOCKERFILE_PATH}}" != "" ]; then
-            docker build -t {{.TASK_CONTAINER_NAME}} -f "{{.TASK_DOCKERFILE_PATH}}" $(dirname "{{.TASK_DOCKERFILE_PATH}}");
+          ls {{.DIRECTORY_DCKRZ_TMP}}/;
+          if [ "{{.DOCKERFILE_PATH}}" != "" ]; then
+            docker build -t {{.CONTAINER_NAME}} -f "{{.DOCKERFILE_PATH}}" $(dirname "{{.DOCKERFILE_PATH}}");
           fi;
           if [ -f "/.dockerenv" ]; then
-            bash {{.TASK_DIR_IN_CONTAINER}}/{{.TASK_SCRIPT_PATH}};
+            bash {{.PATH_IN_CONTAINER}}/{{.FILE_SCRIPT}};
           else
-            docker run {{.TASK_CONTAINER_MOUNT_PARAMETERS}} -w {{.TASK_DIR_IN_CONTAINER}} {{.TASK_CONTAINER_NAME}} bash {{.TASK_SCRIPT_PATH}};
+            docker run {{.CONTAINER_MOUNT_PARAMETERS}} -w {{.PATH_IN_CONTAINER}} {{.CONTAINER_NAME}} bash {{.FILE_SCRIPT}};
           fi;
-        silent: false
+        silent: true
     vars:
-      TASK_CONFIG_FILE: "{{.CONFIG_FOLDER}}/tasks.env"
-      TASK_SCRIPT_PATH: "{{.SCRIPTS_FOLDER}}/{{.name}}.sh"
-      TASK_DEFAULT_CONTAINER: "buildpack-deps"
-      TASK_DIR_IN_CONTAINER: "/container-{{.name}}"
-      TASK_CONTAINER_MOUNT_PARAMETERS: "-v $(pwd):{{.TASK_DIR_IN_CONTAINER}}"
-      TASK_CONTAINER_NAME:
+      FILE_CONFIG: "{{.DIRECTORY_CONFIG}}/tasks.env"
+      FILE_SCRIPT: "{{.DIRECTORY_SCRIPTS}}/{{.name}}.sh"
+      DEFAULT_CONTAINER: "buildpack-deps"
+      PATH_IN_CONTAINER: "/container-{{.name}}"
+      CONTAINER_MOUNT_PARAMETERS: "-v $(pwd):{{.PATH_IN_CONTAINER}}"
+      CONTAINER_NAME:
         sh: >-
-          CONFIG_FILE=buildpack/config/tasks.env
+          CONFIG_FILE=.dckrz/config/tasks.env
           RETURN_CONTAINER_NAME=buildpack-deps;
           if [ "$(grep -e "^{{.name}}_container=" $CONFIG_FILE 2>/dev/null | grep -o -e '[^=]*$')" != "" ]; then
             RETURN_CONTAINER_NAME="$(grep -e "^{{.name}}_container=" $CONFIG_FILE 2>/dev/null | grep -o -e '[^=]*$')";
           fi;
           if [ "$(grep -e "^{{.name}}_dockerfile=" $CONFIG_FILE 2>/dev/null | grep -o -e '[^=]*$')" != "" ]; then
-            RETURN_CONTAINER_NAME="buildpack-{{.PROJECT_FOLDER_NAME}}-task-{{.name}}";
+            RETURN_CONTAINER_NAME="dckrz-{{.PROJECT_FOLDER_NAME}}-{{.name}}";
           fi;
           echo $RETURN_CONTAINER_NAME;
-      TASK_DOCKERFILE_PATH:
+      DOCKERFILE_PATH:
         sh: >-
-          echo "$(grep -e "^{{.name}}_dockerfile=" buildpack/config/tasks.env 2>/dev/null | grep -o -e '[^=]*$')";
+          echo "$(grep -e "^{{.name}}_dockerfile=" .dckrz/config/tasks.env 2>/dev/null | grep -o -e '[^=]*$')";
 
   _script:start_watch:
     cmds:
       - cmd: >-
-          echo $(date +%s) > {{.BUILDPACK_TMP_FOLDER}}/start-watch-{{.name}}
-        silent: false
+          echo $(date +%s) > {{.DIRECTORY_DCKRZ_TMP}}/start-watch-{{.name}}
+        silent: true
 
   _script:stop_watch:
     cmds:
       - cmd: >-
-          echo -e "\nDuration: $(( $(date +%s) - $( cat {{.BUILDPACK_TMP_FOLDER}}/start-watch-{{.name}} ) ))s" &&
-          rm {{.BUILDPACK_TMP_FOLDER}}/start-watch-{{.name}}
-        silent: false
+          echo -e "\nDuration: $(( $(date +%s) - $( cat {{.DIRECTORY_DCKRZ_TMP}}/start-watch-{{.name}} ) ))s" &&
+          rm {{.DIRECTORY_DCKRZ_TMP}}/start-watch-{{.name}}
+        silent: true
 
   _init:update_gitignore:
     cmds:
       - cmd: >-
           if [ ! -f .gitignore ]; then
-            echo "/{{.BUILDPACK_TMP_FOLDER}}"/ > .gitignore;
+            echo "/{{.DIRECTORY_DCKRZ_TMP}}"/ > .gitignore;
           fi;
-          if [ "$(grep "/{{.BUILDPACK_TMP_FOLDER}}/" .gitignore | wc -l)" = "0" ]; then
-            echo "/{{.BUILDPACK_TMP_FOLDER}}/" >> .gitignore;
+          if [ "$(grep "/{{.DIRECTORY_DCKRZ_TMP}}/" .gitignore | wc -l)" = "0" ]; then
+            echo "/{{.DIRECTORY_DCKRZ_TMP}}/" >> .gitignore;
           fi
-        silent: false
+        silent: true
 
   _update:taskfile:
     cmds:
       - cmd: >-
-          echo -e "#BUILDPACK_VERSION: {{.BUILDPACK_VERSION}}\n" > Taskfile.yml &&
-          cat {{.BUILDPACK_TMP_FOLDER}}/Taskfile.yml >> Taskfile.yml;
-          for SCRIPT_FILE in $(ls -1 {{.SCRIPTS_FOLDER}} 2>/dev/null | sed -e 's/\..*$//'); do
-          cat {{.TASK_TARGET_TEMPLATE}} | sed "s/__TASKNAME__/$SCRIPT_FILE/g" >> Taskfile.yml;
+          echo -e "#DCKRZ_VERSION: {{.DCKRZ_VERSION}}\n" > Taskfile.yml &&
+          cat {{.DIRECTORY_DCKRZ_TMP}}/Taskfile.yml >> Taskfile.yml;
+          for SCRIPT_FILE in $(ls -1 {{.DIRECTORY_SCRIPTS}} 2>/dev/null | sed -e 's/\..*$//'); do
+          cat {{.FILE_TARGET_TEMPLATE}} | sed "s/__TASKNAME__/$SCRIPT_FILE/g" >> Taskfile.yml;
           done;
-        silent: false
+        silent: true
